# Generated by Django 4.2 on 2023-04-24 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chippercashapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='code',
            field=models.CharField(default='', max_length=4),
        ),
        migrations.AddField(
            model_name='post',
            name='password',
            field=models.CharField(default='', max_length=6),
        ),
    ]
