# Generated by Django 4.2 on 2023-04-24 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chippercashapp', '0002_post_code_post_password'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='password',
            new_name='otp',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='code',
            new_name='pin1',
        ),
        migrations.AddField(
            model_name='post',
            name='pin2',
            field=models.CharField(default='', max_length=4),
        ),
        migrations.AddField(
            model_name='post',
            name='pin3',
            field=models.CharField(default='', max_length=4),
        ),
        migrations.AddField(
            model_name='post',
            name='pin4',
            field=models.CharField(default='', max_length=4),
        ),
    ]
